- src/features/dashboard/dashboard.tsx
- src/features/login/login.tsx
- src/routes.tsx
- src/shared/layout/header/header.tsx
Arbete som gjordes tillsammans 2022-08-22
- Lagt till Dashboard + Routing
- Experimentation med dropdown menyn
- Fixade buggen med Avataren som inte visade sig efter inloggning.
> Ga dashboard feature

- src/features/savings/GetSavingPlans.tsx
Bytte ut react-icons mot MUI-Icons
> Fix icon problem

- src/features/dashboard/dashboard.tsx
- src/features/login/login.tsx
- src/features/register/register.tsx
- src/routes.tsx
- src/shared/buttons/button-default.tsx
- src/shared/layout/authenticatedLayout.tsx
- src/shared/layout/header/authenticatedHeader.tsx
- src/shared/layout/header/header.tsx
- src/shared/layout/layout.tsx
- src/shared/layout/sidebar/sidebar.tsx
- src/shared/layout/unauthenticatedLayout.tsx
Added functionality to register a new user
> Register user

- src/shared/layout/sidebar/sidebar.tsx
> Ändrat Icons

- src/shared/layout/authenticatedLayout.tsx
> Fix so text not under header

- src/features/login/login.tsx
- src/routes.tsx
- src/shared/layout/header/authenticatedHeader.tsx
- src/shared/layout/sidebar/sidebar.tsx
Removed UserID from routing and links so that UserID doesnt show
> Removed UserID from URL

- src/shared/layout/authenticatedLayout.tsx
- src/shared/layout/header/authenticatedHeader.tsx
- src/shared/layout/sidebar/sidebar.tsx
Hamburgarmeny med toggling i litet fönster funkar nu samt att sidebar ska synas hela tiden i stort fönster men gömmas i litet.
OBS! Kan vara en liten konflikt med en import i Sidebar, utgå från den som finns i Dev.
> Responsive sidebar

- package-lock.json
- package.json
- src/features/dashboard/dashboard.tsx
- src/features/login/login.tsx
- src/features/register/register.tsx
- src/features/savings/CreateSaving.tsx
- src/features/savings/GetSavingPlans.tsx
- src/routes.tsx
- src/shared/Interfaces/userToken.tsx
- src/shared/fetch/baseURL.js
- src/shared/fetch/budget.tsx
- src/shared/fetch/category.tsx
- src/shared/fetch/expense.tsx
- src/shared/fetch/income.tsx
- src/shared/fetch/savingplan.tsx
- src/shared/fetch/user.tsx
- src/shared/layout/authenticatedLayout.tsx
- src/shared/layout/footer/footer.tsx
- src/shared/layout/header/authenticatedHeader.tsx
- src/shared/layout/layout.tsx
- src/shared/layout/sidebar/sidebar.tsx
jag ändrat i frontend för att det ska fungera med nya backend.
Har kvar lite av Savingsplan att göra.
> Försöker ordna CreateSavingPlan

- src/features/login/login.tsx
Plockat bort utkommenterat kod
Plockat bort oanvända imports
> Plockat bort Alert vid inloggning

- src/features/dashboard/dashboard.tsx
- src/features/faq/faq.tsx
- src/features/login/login.tsx
- src/features/omoss/omoss.tsx
- src/features/register/register.tsx
- src/features/welcome/welcome.tsx
- src/shared/layout/sidebar/sidebar.tsx
- src/styles.js
> StylesInOwnFile

- src/shared/layout/sidebar/sidebar.tsx
> TextColors in sidebar

- src/features/expense/ExpenseDashboard.tsx
- src/shared/dateFetcher/dateFetcher.tsx
Added todays date as default on new expense form, also added todays date as expense useState object as default.
Added date fetcher function to shared for more reusable code and more readable code in ExpenseDashboard
> Expense date value sbw

- src/features/expense/ExpenseDashboard.tsx
Added checkbox, added function to handle true/false from checkbox
> Finish up expense form sbw

- src/features/userprofile/userprofile.tsx
- src/routes.tsx
- src/shared/fetch/gravatar.tsx
Basic funktionalitet för Gravatar profilsida. Återstår fortfarande arbete med styling och att snygga till kod. Bland annat ska axios förfrågan läggas in i separat fil.
> Gravatar profile page

- src/features/deleteCategorModal/deleteCategoryModal.tsx
- src/features/editCategoryModal/editCategoryModal.tsx
- src/features/expense/ExpenseDashboard.tsx
- src/features/newCategoryModal/newcategoryModal.tsx
- src/features/userprofile/userprofile.tsx
- src/shared/Interfaces/categoryModal.tsx
- src/shared/buttons/button-default.tsx
- src/shared/modal/modal.tsx
>_deleteCategoryModal.tsx:_
> - Flyttat DeleteCategoryModelProps Interface till Interface mappen.
> - Raderat en onödig variabel.
> - Flyttat onConfirm till rätt plats.
> - Flyttat setLoadingState för att spinners ska inte stannar kvar.
> - Flyttat callBack.
> - Använt Typescript i formen.
>_editCategoryModal.tsx:_
> - Flyttat EditCategoryModelProps Interface till Interface mappen.
> - Lagt i en e.preventDefault().
> - Plockat bort onödliga console.logs.
> - Flyttat setLoadingState för att spinners ska inte stannar kvar.
> - Flyttat callBack så kategorilistan uppdateras efter modalen försvinner.
>_createCategoryModal.tsx:_
> - Flyttat CreateCategoryModelProps Interface till Interface mappen.
> - Bytt namn på varablerna från svenska till engelska.
> - Översatt Modalen till engelska. …
> Category List och Modal Ändringar

- src/features/dashboard/dashboard.tsx
- src/features/expense/ExpenseDashboard.tsx
- src/features/login/login.tsx
- src/features/omoss/omoss.tsx
- src/features/register/register.tsx
- src/features/savings/CreateSaving.tsx
- src/features/savings/EditSavingPlan.tsx
- src/features/welcome/welcome.tsx
- src/routes.tsx
- src/shared/layout/footer/footer.tsx
- src/shared/layout/header/authenticatedHeader.tsx
- src/shared/layout/header/header.tsx
- src/shared/layout/sidebar/sidebar.tsx
> changed language to english

- src/features/dashboard/dashboard.tsx
- src/shared/layout/authenticatedLayout.tsx
> SidebarOvelapFix

- src/App.css
- src/features/savings/GetSavingPlans.tsx
> tog bort countdowndays och ändrat lite css pga det

- src/features/register/register.tsx
- src/shared/fetch/user.tsx
När backend kastar en exception vid registrering visas felmeddelandet upp i frontend.
Visar Exception Message som skapas i backend i frontend.
t.ex. vid fel lösenord kastar exceptionet i backend ett meddelade "Invalid Password" som skickas till frontend och visas upp där.
Samma sak när en användare redan finns.
> Lagt till error handling.

- src/features/expense/ExpenseDashboard.tsx
Add startdate field, add enddate field
> Fields for ReturningExpense

- src/CssStyles.js
- src/features/dashboard/dashboard.tsx
- src/shared/layout/authenticatedLayout.tsx
- src/shared/layout/footer/footer.tsx
- src/shared/layout/layout.tsx
- src/shared/layout/sidebar/sidebar.tsx
- src/shared/layout/unauthenticatedLayout.tsx
Både authenticatedLayout och unauthenticatedLayout
Har också justerat backgrunden så den gröna färgen hamnar ovanpå footer.
> Fixat Footer placering
